### PR TITLE
Webpack docs and upgrade notes

### PR DESCRIPTION
**Pull request by pesektomas**
| Q             | A
| ------------- | ---
|Description, reason for the PR| Added docs and upgrades for webpack introduced in #1545 
|New feature| No
|[BC breaks](https://docs.shopsys.com/en/latest/contributing/backward-compatibility-promise/)| No 
|Fixes issues| ...
|Have you read and signed our [License Agreement for contributions](https://www.shopsys.com/license-agreement)?| Yes

### CODE REVIEW

File: upgrade/UPGRADE-v9.0.0-dev.md [hunk 1]
```diff
@@ -561,3 +561,8 @@ There you can find links to upgrade notes for other versions too.
     - don't forget to rebuild your grunt file by command `php phing gruntfile` and update your npm dependencies by command `npm install`
     - to fix all your less files in command line by command `php phing stylelint-fix`
 [shopsys/framework]: https://github.com/shopsys/framework
+
+### Frontend
+
+- javascript assets are manage by webpack and npm ([#1498](https://github.com/shopsys/shopsys/pull/1545))
```
Comment (sslt) [inline upgrade/UPGRADE-v9.0.0-dev.md]: ... are managed ...

File: docs/frontend/frontend-npm-webpack.md [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+## Some use cases
+
+### I want to edit existing javascripts
+
+- you have to run `npm run watch` in project-base (project root). You can run it in docker or on local (when you have installed npm)
+- you can edit files
+- (you may notice changes in the console)
+- you can test changes (after page reload)
+
+### I want to add new javascript file on frontend
```
Comment (sslt) [inline docs/frontend/frontend-npm-webpack.md]: to frontend

File: docs/frontend/frontend-npm-webpack.md [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+
+- you have to run `npm run watch` in project-base (project root). You can run it in docker or on local (when you have installed npm)
+- you can create new javascript file (path of new file is `assets/frontend/myNewFile.js`)
+- you can use this new file in some other file (`import ./frontend/myNewFile.js`)
+- or, when file contains global event listener, import new file in `assets/frontend/app.js` (`import ./myNewFile.js`)
+
+### I want to add new javascript file on admin
```
Comment (sslt) [inline docs/frontend/frontend-npm-webpack.md]: ... to administration

File: docs/frontend/frontend-npm-webpack.md [hunk 4]
```diff
@@ -0,0 +1,116 @@
...
+
+To compile the code into something the browser understands we run the code through Webpack. These build/compile operations are provided as npm script to make them easy to run.
+
+We configure a webpack with a webpack encore.
+
+## How do we use them?
+
+When working with a javascripts and friends packages you should have a package.json in the root directory of your project. This declares all required dependencies to run your package (In PHP, this is similar to a composer.json file).
+
+To install all dependencies you should run `npm install` in the root directory of your project. This installs all third party dependencies in the /node_modules directory. (In PHP, this is similar to running composer). Every time you pull down new code you should ensure that all dependencies are installed or you will get errors such as Error Cannot find module 'foo' when you try to build your application. Phing target `npm` downloads packages and run build script. To add a new library, use the npm install command (for example, `npm install counterup2`).
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
To install all dependencies you should run `npm install` in the root directory of your project. This installs all third party dependencies in the `/node_modules` directory (in PHP, this is similar to running composer). Every time you pull down new code you should ensure that all dependencies are installed or you will get errors such as `Error Cannot find module 'foo'` when you try to build your application. Phing target `npm` downloads packages and run build script. To add a new library, use the npm install command (for example, `npm install counterup2`) or phing target `php phing npm`.
```

File: docs/frontend/frontend-npm-webpack.md [hunk 5]
```diff
@@ -0,0 +1,116 @@
...
+Once a dependency is installed you can use it in a JS file in your application. For example, if you install counterup2 you can import and use it:
+
+```js
+// assets/frontend/components/counterUpInit.js
+import counterUp from 'counterup2';
+
+export default function counterUpInit () {
+    document.querySelectorAll('.js-counter').forEach(counterItem => {
+        counterUp(counterItem, {
+            ...
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
            // ...
```

File: docs/frontend/frontend-npm-webpack.md [hunk 6]
```diff
@@ -0,0 +1,116 @@
...
+        })
+    }
+}
+```
+
+When compiling your application the process is clever enough to understand when a dependency has already been imported from a different file - meaning that everything is ultimately only ever imported once. However, by having to import dependencies into each file, you ensure that that particular file will work independently.
+
+If you want to add a new component that will listen to a certain event (for example), you have to import the component in the main file. For project-base, this is the `assets/frontend/app.js` file, for the administration is the` assets/admin/admin.js` file. The addition works just like a component installed over npm except that relative paths are used.
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
If you want to add a new component that will listen to a certain event (for example), you have to import the component in the main file. For project-base, this is the `assets/frontend/app.js` file, for the administration is the ` assets/admin/admin.js` file. The addition works just like a component installed over npm except that relative paths are used.
```

File: docs/frontend/frontend-npm-webpack.md [hunk 7]
```diff
@@ -0,0 +1,116 @@
...
+
+```js
+    // assets/frontend/app.js
+    import './components/counterUpInit';
+    ...
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
    // ...
```

File: docs/frontend/frontend-npm-webpack.md [hunk 8]
```diff
@@ -0,0 +1,116 @@
...
+```
+
+When we are editing a javascripts and friends files, the change must go through the bundler (webpack). All javascripts and friends files are built using the `npm run build` command. But it would be impractical if we had to run a command in the console with every change. Therefore we can use `npm run watch` for development. This command checks if a file has changed and if it changes it adds the changes to the resulting bundle. The `npm run watch` command launches the webpack in development mode, which means creating source maps to help you debug your project.
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
When we are editing a javascript and friends files, the change must go through the bundler (webpack). All javascript and friends files are built using the `npm run build` command. But it would be impractical if we had to run a command in the console with every change. Therefore we can use `npm run watch` for development. This command checks if a file has changed and if it changes it adds the changes to the resulting bundle. The `npm run watch` command launches the webpack in development mode, which means creating source maps to help you debug your project.
```

File: docs/frontend/frontend-npm-webpack.md [hunk 9]
```diff
@@ -0,0 +1,116 @@
...
+
+## Some use cases
+
+### I want to edit existing javascripts
+
+- you have to run `npm run watch` in project-base (project root). You can run it in docker or on local (when you have installed npm)
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to run `npm run watch` in the project root. You can run it in docker or on local (when you have installed npm)
```

Documentation should be written from a point of project.

File: docs/frontend/frontend-npm-webpack.md [hunk 10]
```diff
@@ -0,0 +1,116 @@
...
+- you can edit files
+- (you may notice changes in the console)
+- you can test changes (after page reload)
+
+### I want to add new javascript file on frontend
+
+- you have to run `npm run watch` in project-base (project root). You can run it in docker or on local (when you have installed npm)
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to run `npm run watch` in the project root. You can run it in docker or on local (when you have installed npm)
```

File: docs/frontend/frontend-npm-webpack.md [hunk 11]
```diff
@@ -0,0 +1,116 @@
...
+- you can create new javascript file (path of new file is `assets/frontend/myNewFile.js`)
+- you can use this new file in some other file (`import ./frontend/myNewFile.js`)
+- or, when file contains global event listener, import new file in `assets/frontend/app.js` (`import ./myNewFile.js`)
+
+### I want to add new javascript file on admin
+
+- you have to run `npm run watch` in project-base (project root). You can run it in docker or on local (when you have installed npm)
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to run `npm run watch` in the project root. You can run it in docker or on local (when you have installed npm)
```

File: docs/frontend/frontend-npm-webpack.md [hunk 12]
```diff
@@ -0,0 +1,116 @@
...
+- you can create new javascript file (path of new file is `assets/admin/myNewFile.js`)
+- you can use this new file in some other file (`import ./admin/myNewFile.js`)
+- or, when file contains global event listener, import new file in `assets/admin/admin.js` (`import ./myNewFile.js`)
+
+### I want to add new package from other developer
+
+- you have to stop `npm run watch` (when it is running)
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to stop `npm run watch` (if it is running)
```

File: docs/frontend/frontend-npm-webpack.md [hunk 13]
```diff
@@ -0,0 +1,116 @@
...
+- you can add package via npm `npm install <package-name>`
+- you have to run `npm run watch` in project-base (project root). You can run it in docker or on local (when you have installed npm)
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to run `npm run watch` in the project root. You can run it in docker or on local (when you have installed npm)
```

File: docs/frontend/frontend-npm-webpack.md [hunk 14]
```diff
@@ -0,0 +1,116 @@
...
+- you can use new package (`import <package-name>` in some file)
+- you can test changes (after page reload)
+
+### I want to override function from @shopsys/framework common package
+
+For example, we can override method `showFormErrorsWindowOnFrontend` from `@shopsys/framework/common/validation/customizeBundle.js` on frontend.
+
+- you have to run `npm run watch` in project-base (project root). You can run it in docker or on local (when you have installed npm)
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to run `npm run watch` in the project root. You can run it in docker or on local (when you have installed npm)
```

File: docs/frontend/frontend-npm-webpack.md [hunk 15]
```diff
@@ -0,0 +1,116 @@
...
+- you have to import CustomizeBundle in `assets/frontnd/app.js`
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to import CustomizeBundle in `assets/frontend/app.js`
```

File: docs/frontend/frontend-npm-webpack.md [hunk 16]
```diff
@@ -0,0 +1,116 @@
...
+```js
+import CustomizeBundle from 'framework/common/validation/customizeBundle';
+...
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
// ...
```

File: docs/frontend/frontend-npm-webpack.md [hunk 17]
```diff
@@ -0,0 +1,116 @@
...
+```
+- you can prepare new function
+```js
+const myOverridedShowFormErrorsWindow = (container) => {
+    console.log('Hello my overrided showFormErrorsWindow method.');
+}
+```
+- you have to replace original method as your new one
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
- you have to replace the original method with the new one
```

File: docs/frontend/frontend-npm-webpack.md [hunk 18]
```diff
@@ -0,0 +1,116 @@
...
+import CustomizeBundle from 'framework/common/validation/customizeBundle';
+
+const myOverridedShowFormErrorsWindow = (container) => {
+    console.log('Hello my overrided showFormErrorsWindow method.');
+}
+
+CustomizeBundle.showFormErrorsWindow = myOverridedShowFormErrorsWindow;
+```
+
+This princip is call Monkey Patching and you can read more on [this](https://www.sitepoint.com/pragmatic-monkey-patching/) article.
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
This principle is called [Monkey Patching](https://www.sitepoint.com/pragmatic-monkey-patching/).
```

File: docs/frontend/index.md [hunk 19]
```diff
@@ -1,6 +1,7 @@
 # Frontend
 
 ## Getting started
+* [Introduction to npm, webpack and webpack encore](frontend-npm-webpack.md)
```
Comment (grossmannmartin) [inline docs/frontend/index.md]:
```suggestion
* [Introduction to npm, webpack and webpack encore](./frontend-npm-webpack.md)
```

to be unified with other links

File: docs/frontend/frontend-npm-webpack.md [hunk 20]
```diff
@@ -0,0 +1,116 @@
+# Modern frontend
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]: According to our [guidelines for writing documentation](https://docs.shopsys.com/en/9.0/contributing/guidelines-for-writing-documentation/)

> All documentation files should be named same as first heading (in lowercase, non-alphanumeric characters replaced by dash).

File: docs/frontend/frontend-npm-webpack.md [hunk 21]
```diff
@@ -0,0 +1,116 @@
...
+
+A [webpack](https://webpack.js.org/) is a bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the application on demand.
+
+A [webpack encore](https://github.com/symfony/webpack-encore) is powerful API for processing & compiling assets built around Webpack.
+
+## What do we use them for?
+
+We use npm to manage and install frontend packages. We use npm also for maintain common scripts at [@shopsys/framework](https://www.npmjs.com/~shopsys_framework).
+
+To compile the code into something the browser understands we run the code through Webpack. These build/compile operations are provided as npm script to make them easy to run.
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
To compile the code into something the browser understands we bundle the code through Webpack. These build/compile operations are provided as npm script to make them easy to run.
```

File: docs/frontend/frontend-npm-webpack.md [hunk 22]
```diff
@@ -0,0 +1,116 @@
...
+
+We configure a webpack with a webpack encore.
+
+## How do we use them?
+
+When working with a javascripts and friends packages you should have a package.json in the root directory of your project. This declares all required dependencies to run your package (In PHP, this is similar to a composer.json file).
```
Comment (grossmannmartin) [inline docs/frontend/frontend-npm-webpack.md]:
```suggestion
When working with a javascripts and friends packages you should have a `package.json` file in the root directory of your project. This file declares all required dependencies to run your package (In PHP, this is similar to a `composer.json` file).
```

File: docs/frontend/frontend-npm-webpack.md [hunk 23]
```diff
@@ -0,0 +1,116 @@
+# Modern frontend
+
+## Introduction to npm, webpack and webpack encore
+
+A [npm](https://www.npmjs.com/) is a package manager it allows you to install javascripts packages from other developers and to eventually publish your own packages.
+
+A [webpack](https://webpack.js.org/) is a bundler for javascript and friends. Packs many modules into a few bundled assets. Code Splitting allows for loading parts of the application on demand.
```
[the remark this answers is not in the document]
Comment (pesektomas) [reply docs/frontend/frontend-npm-webpack.md]: A read this construct on some blog in past and I liked it. Webpack working with another file types too. I hope that we will use it for less files and static images in near future. But it is my mindset, we can change it.

File: upgrade/upgrade-instruction-for-webpack.md [hunk 24]
```diff
@@ -0,0 +1,1212 @@
...
+```diff
+webpack_encore:
+    output_path: '%kernel.project_dir%/web/build'
+```
+
+- Move all scripts from src/Resources/scripts to assets/js
+
+- Remove folder assets/js/plugins (plugins are load from npm)
+
+- Update your package.json
```
[the remark this answers is not in the document]
Comment (pesektomas) [reply upgrade/upgrade-instruction-for-webpack.md]: I added step with run `npm install`

File: upgrade/upgrade-instruction-for-webpack.md [hunk 25]
```diff
@@ -0,0 +1,1212 @@
...
+```dif
+     "name": "shopsys",
++    "scripts": {
++        "dev-server": "encore dev-server",
++        "dev": "encore dev",
++        "watch": "encore dev --watch",
++        "build": "encore production --progress",
++        "trans": "./assets/js/bin/trans.js",
++        "copyFw": "./assets/js/bin/copyFw.js"
```
[the remark this answers is not in the document]
Comment (pesektomas) [reply upgrade/upgrade-instruction-for-webpack.md]: You are right, thx

File: docs/frontend/frontend-npm-webpack.md (hunk 23 above)
[the remark this answers is not in the document]
Comment (grossmannmartin) [reply docs/frontend/frontend-npm-webpack.md]: I see it's used in https://github.com/webpack/webpack so I cannot argue against :)
